DOMAIN = "simple_wyze_vac"
WYZE_VAC_CLIENT = "simple_wyze_vac_client"
WYZE_VACUUMS = "simple_wyze_vacuums"
WYZE_USERNAME = "simple_wyze_vac_username"
WYZE_PASSWORD = "simple_wyze_vac_password"
WYZE_SCAN_INTERVAL = "simple_wyze_vac_scan_interval"
CONF_POLLING = "poll"
CONF_TOTP = "totp"
